repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        files: \.(yaml|yml)$
  - repo: local
    hooks:
      - id: pytest
        name: Run tests with pytest
        entry: pytest
        language: system
        pass_filenames: false
