name: Update PR Lifecycle Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_pr_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Accumulate PR Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python accumulate_pr_data.py

      - name: Plot PR Delays
        run: python plot_pr_delays.py

      - name: Commit updated CSV and plot
        run: |
          git config user.name "github-actions"
          git config user.email "xlsynth-github-actions@xlsynth.org"
          git add pr_data.csv pr_delays.png
          if ! git diff --quiet --cached; then
            git commit -m "Automatic update: PR data and plot"
            git push
          else
            echo "No changes to commit."
          fi
